### PR TITLE
#69-challenge-is-even

### PR DESCRIPTION
**Pull request by Carlos00004**

### CODE REVIEW

**Review by CRBM84 — APPROVED** [review]

**Review by Portaltocoding — CHANGES_REQUESTED** [review]
<p>Hi there, I found your code working for all cases scenarios but one related to strings: When its accepting a string or a list of characters it is counting them all + the white spaces, that I do suppose are not meant to be counted;  with just adding the method .trim( )   you can solve it.</p>

##### Great work! 👍 🍰 🍰 

4not4chars

**Comment by CarlosLemonCode** [comment]
> Hi there, I found your code working for all cases scenarios but one related to strings: When its accepting a string or a list of characters it is counting them all + the white spaces, that I do suppose are not meant to be counted; with just adding the method .trim( ) you can solve it.
> 
> ##### Great work! 👍 🍰 🍰


Thanks mate! It should works well now.

**Review by CRBM84 — APPROVED** [review]
👏🏼

**Review by Portaltocoding — COMMENTED** [review]
Super💻💪

**Review by Portaltocoding — APPROVED** [review]

**Review by venturars — APPROVED** [review]

**Pull request merged**
