### PR TITLE
#91-challenge-is-even

### PR DESCRIPTION
**Pull request by angelabernaldz**

### CODE REVIEW

**Review by CRBM84 — CHANGES_REQUESTED** [review]
Hi, your variable, hasn't been manipulated, I am getting a failure message on the testing parameters. Perhaps you haven't pushed through your latest code.

**Comment by angelabernaldz** [comment]
> Hi, your variable, hasn't been manipulated, I am getting a failure message on the testing parameters. Perhaps you haven't pushed through your latest code.

Hi Carlos, thank you for your comment. Indeed, I have not modified the initial code given to us so the current version does not work. Just wanted to upload the statement to know what the challenge was. Will request your review as soon as it is finished, thank you.

**Comment by angelabernaldz** [comment]
Hello, could you please have a look at this PR now that I've finished solving the exercise? Thank you

**Review by CarlosLemonCode — APPROVED** [review]
Nada que añadir! 😁👌

**Review by venturars — APPROVED** [review]
Perfecto, mejor no dejar console.log() sueltos pero lo veo todo ok

**Pull request merged**
