### PR TITLE
#36-challenge-binary-to-decimal

### PR DESCRIPTION
**Pull request by LeideVanessaC**

### CODE REVIEW

**Review by CRBM84 — CHANGES_REQUESTED** [review]
I think you need to modify the function so that it converts the number to decimal

**Comment by LeideVanessaC** [comment]
> I think you need to modify the function so that it converts the number to decimal

I hope I have corrected the code. I have to study more function!

**Comment by CarlosLemonCode** [comment]
Finally you did it! The code works great. 👍

**Review by Carlos00004 — APPROVED** [review]
👍 👍 👍

**Review by CRBM84 — APPROVED** [review]
Perfect

**Review by CRBM84 — APPROVED** [review]
Gracias por borrar el gitignore, tu código pasa la prueba.

**Review by CRBM84 — CHANGES_REQUESTED** [review]
Por favor has un git add para borrar el gitignore

**Review by CarlosLemonCode — CHANGES_REQUESTED** [review]
Intenta arreglar el archivo .gitignore! :) 👍

**Review by rucev — APPROVED** [review]
👍

**Pull request merged**
